Phase 1A TEMPORARY HACK: init() manually switching to PID 1.
phase2_start_service_processes() called -- currently a NOP
phase3_start_service_processes() called -- currently a NOP
phase4_start_service_processes() called -- currently a NOP
phase5_start_service_processes() called -- currently a NOP
Phase 1A TEMPORARY HACK: init() manually switching to testcase_main() after using spork() to create it.
testcase_main(): started
EXPECTATION: main() creates XXp1.  XXp1 creates XXp2, and then immediately returns before calling join(); the Phase 1 code should thus call quit() on that process.  Although XXp2 is higher priority than XXp1 (meaning that it ran to completion before this code ran), the code should complain because you quit() a process before calling join() on all of your children.
Phase 1A TEMPORARY HACK: Manually switching to XXp1()
Phase 1A TEMPORARY HACK: Manually switching to XXp2()
XXp2(): started
XXp2(): arg = 'XXp2'
XXp2(): terminating!
XXp1(): spork() rc=4
Dump Process    1  init     6     0     1
    2 testcase_main     3     0     0
    3  XXp1     2     0     0
    4  XXp2     1     0    -2
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
    0           0     0     0
XXp1(): This process will terminate.  This should cause an error check in quit() to fire, report an error, and kill the simulation.
********************
* TESTCASE FAILURE *
********************
If you ever see this error message, then it means that you don't have sufficient error checking in quit().
Phase 1A TEMPORARY HACK: testcase_main() returned, simulation will now halt.
finish(): The simulation is now terminating.
